
networks: 
  artisan_des_saveurs_net:
    driver: bridge

services:
  dev-db:
    image: mysql:8.1
    container_name: res-artisan_des_saveurs_dev
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - artisan_des_saveurs_net
    volumes:
      - dev_db_data:/var/lib/mysql

  prod-db:
    image: mysql:8.1
    container_name: res-artisan_des_saveurs_prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    networks:
      - artisan_des_saveurs_net
    volumes:
      - prod_db_data:/var/lib/mysq
  adminer:
    image: adminer
    container_name: adminer_artisan
    restart: always
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: dev-db
    networks:
      - artisan_des_saveurs_net
    depends_on:
      - dev-db


volumes:
  dev_db_data:
  prod_db_data:
