on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests
        env:
          NODE_ENV: test
          MYSQLHOST: 127.0.0.1
          MYSQLPORT: 3306
          MYSQLUSER: root
          MYSQLPASSWORD: dev-root
          MYSQL_DATABASE: test_artisan_des_saveurs_db
          JWT_SECRET: secret_for_ci
          ADMIN_NAME: TestAdmin
          ADMIN_EMAIL: testadmin@example.com
          ADMIN_PASSWORD: TestPassword123
        run: npm test
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: dev-root
          MYSQL_DATABASE: test_artisan_des_saveurs_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
